---
title: "Lavaan tutorial"
author: "Zoë Hawks"
date: "10/20/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message = FALSE}
library(lavaan)
library(tidyverse)
library(XML)
library(OpenMx)
library(semPlot)
```

## Model 1: CFA
```{r, warning = F, message = F}
CFA.mod <- ' 
            visual =~ x1 + x2 + x3
            textual =~ x4 + x5 + x6
            speech =~ x7 + x8 + x9 
'

fit <- cfa(CFA.mod, data=HolzingerSwineford1939)
summary(fit, fit.measures = TRUE)
semPaths(fit, whatLabels = "est")
```

## Model 2: SEM
```{r, warning = F}
SEM.mod <- '
    ind60 =~ x1 + x2 + x3         #indicators onto latent variables
    dem60 =~ y1 + y2 + y3 + y4
    dem65 =~ y5 + y6 + y7 + y8
  
    dem60 ~ ind60                 #regression equations
    dem65 ~ ind60 + dem60
  
    y1 ~~ y5                      #residual correlations
    y2 ~~ y4 + y6
    y3 ~~ y7
    y4 ~~ y8
    y6 ~~ y8
'

fit <- sem(SEM.mod, data=PoliticalDemocracy)
summary(fit, standardized=TRUE)
semPaths(fit, whatLabels = "est")
```

## Syntax, cont.
```{r, warning = F}
# if you want to constrain all COVARIANCES of latent variables to zero, 'orthogonal = TRUE'
fit <- cfa(CFA.mod,
                    data = HolzingerSwineford1939,
                    orthogonal = TRUE)
summary(fit, fit.measures = TRUE)

# if you want to constrain all VARIANCES of latent variables to zero, 'std.lv = TRUE'
fit <- cfa(CFA.mod,
                    data = HolzingerSwineford1939,
                    std.lv = TRUE)
summary(fit, fit.measures = TRUE)
coef1 <- broom::tidy(coef(fit))
coef1

# Playing around with paramter lavels
# Note: providing starting value != fixing factor loading
CFA.mod <- ' 
            visual =~ x1 + x2 + HEY*x3
            textual =~ x4 + x5 + x6
            speech =~ x7 + YO*x8 + start(0.9)*x9 
'
fit <- cfa(CFA.mod, data = HolzingerSwineford1939)
summary(fit, fit.measures = TRUE)
coef1 <- broom::tidy(coef(fit))
coef1

# Specifying equality -- x3, x8, and x9 all the same
CFA.mod <- ' 
            visual =~ x1 + x2 + a*x3
            textual =~ x4 + x5 + x6
            speech =~ x7 + a*x8 + a*x9 
'
fit <- cfa(CFA.mod, data = HolzingerSwineford1939)
summary(fit, fit.measures = TRUE)

# Setting constraints
set.seed(1234)
mydata <- data.frame(y = rnorm(100),
                   x1 = rnorm(100),
                   x2 = rnorm(100),
                   x3 = rnorm(100))

new.mod <- ' y ~ b1*x1 + b2*x2 + b3*x3    # model 
                 
            b1 == (b2 + b3)^2             # constraints
            b1 > exp(b2 + b3) '
fit <- sem(new.mod, data=mydata)
summary(fit)

# Bringing in the means

  # can fix intercepts, e.g. variable ~ 1
  # can specify 'meanstructure = TRUE' when fitting model
  # by default, sem() and cfa() fix latent variable intercepts to zero
  # In practice, the only reason why a user would add intercept-formulas in the model syntax, is because        some constraints must be specified on them. For example, suppose that we wish to fix the intercepts of      the variables x1, x2, x3 and x4 to, say, 0.5. 
```

## Multiple groups
```{r, warning = FALSE}
# add 'group' argument within fit formula --> able to estimate different fits for different groups
fit <- cfa(CFA.mod,
           data = HolzingerSwineford1939,
           group = "school")
summary(fit)

# If you want to fix parameters, or provide starting values, you can use the same pre-multiplication techniques, but the single argument is now replaced by a vector of arguments, one for each group. 
Group.mod <- '  
              visual =~ .5*x1 + c(a,a)*x2 + c(a,a)*x3
              textual =~ x4 + x5 + c(.5, .7)*x6
              speed   =~ c(1, NA)*x7 + x8 + x9 
'
fit <- cfa(Group.mod,
           data = HolzingerSwineford1939,
           group = "school")
summary(fit)

# What if we want constraints for a large number of parameters to be equal across groups?
# Use 'group.equal' argument within fit function
# For 'group.equal,' might also specify: intercepts, means, residuals, residual.covariances, lv.variances, lv.covariances, regressions
fit <- cfa(CFA.mod,
           data = HolzingerSwineford1939,
           group = "school",
           group.equal = c("loadings"))
summary(fit)

# What if we want all but a few constraints to be equal across groups?
# Use 'group.partial' argument within fit function to specify parameters that should remain free
fit <- cfa(CFA.mod,
           data = HolzingerSwineford1939,
           group = "school",
           group.equal = c("loadings", "intercepts"),
           group.partial = c("visual=~x2", "x7~1"))

# Measurement invariance
# To test the measurement invariance of a CFA model across several groups; each model is compared to the baseline model and the previous model using chi-square difference tests.
library(semTools)
measurementInvariance(CFA.mod,
                      data = HolzingerSwineford1939,
                      group = "school")
```

##Growth curve models
```{r, warning = FALSE}
# Random effects are used to capture individual differences. The random effects are conveniently represented by (continuous) latent variables, often called growth factors (??)

# linear growth model with 4 timepoints
# to specify intercept: coefficients stable across timepoints
# to specify slope: coefficients increment across timepoints
Growth.mod <- ' i =~ 1*t1 + 1*t2 + 1*t3 + 1*t4 
            s =~ 0*t1 + 1*t2 + 2*t3 + 3*t4 '
fit <- growth(Growth.mod, data=Demo.growth)
summary(fit)

# a linear growth model with a time-varying covariate (c) and two regressors (x1 & x2) that influence the latent growth factors
model <- '
  # intercept and slope with fixed coefficients
    i =~ 1*t1 + 1*t2 + 1*t3 + 1*t4
    s =~ 0*t1 + 1*t2 + 2*t3 + 3*t4
  # regressions
    i ~ x1 + x2
    s ~ x1 + x2
  # time-varying covariates
    t1 ~ c1
    t2 ~ c2
    t3 ~ c3
    t4 ~ c4
'
fit <- growth(model, data = Demo.growth)
summary(fit)

semPaths(fit, rotation = 3, exoVar = FALSE)
```

## Categorical variables
```{r}
# exogenous ~ independent, endogenous ~ dependent
# if exogenous categorical variable, treat as normal regression (e.g., dummy code)
# if endogenous categorical variable, need to either (1) delcare variables "ordered" or (2) specifiy as order within the fit function. e.g.:

#where items 1-4 are your binary/ordered variables 
# fit <- cfa(myModel, data = myData,
#            ordered=c("item1","item2",
#                      "item3","item3")) 
```

## Using covariance matrix as input
```{r}
lower <- '
 11.834
  6.947   9.364
  6.819   5.091  12.532
  4.783   5.028   7.495   9.986
 -3.839  -3.889  -3.841  -3.625  9.610
-21.899 -18.831 -21.748 -18.775 35.522 450.288 '

wheaton.cov <-
    getCov(lower, names = c("anomia67", "powerless67",
                            "anomia71", "powerless71",
                            "education", "sei"))

wheaton.cov

wheaton.model <- '
                                            #latent variables
    ses     =~ education + sei              
    alien67 =~ anomia67 + powerless67
    alien71 =~ anomia71 + powerless71
                                            #regressions
    alien71 ~ alien67 + ses
    alien67 ~ ses
                                            #correlated residuals
    anomia67 ~~ anomia71
    powerless67 ~~ powerless71
'
fit <- sem(wheaton.model,
           sample.cov = wheaton.cov,
           sample.nobs = 932)               #need to specify number of observations
summary(fit, standardized = TRUE)
semPaths(fit)
```

## Estimators, standard errors, and missing values
```{r}
# Estimators: ML (default), GLS, WLS, DWLS, ULS
# ML estimation -- default is biased (n); if you want unbiased (n-1), use argument likelihood = "wishart"

fit <- cfa(CFA.mod,
           data = HolzingerSwineford1939,
           likelihood = "wishart")
summary(fit)

# Page 32 of tutorial: information about missing values, standard errors, and bootstrapping in Lavaan
```

## Indirect effects & mediation
```{r}
#create fake dataset on which to conduct mediation analysis
set.seed(1234)
X <- rnorm(100)
M <- 0.5*X + rnorm(100)
Y <- 0.7*M + rnorm(100)
Data <- data.frame(X = X, Y = Y, M = M)

model <- ' # direct effect
             Y ~ c*X
           # mediator
             M ~ a*X
             Y ~ b*M
           # indirect effect (a*b)
             ab := a*b
           # total effect
             total := c + (a*b)
         '
fit <- sem(model, data = Data)
summary(fit)
semPaths(fit, layout = "tree2", rotation = 2)

# The example illustrates the use of the ":=" operator in the lavaan model syntax. This operator ‘defines’ new parameters which take on values that are an arbitrary function of the original model parameters. The function, however, must be specified in terms of the parameter labels that are explicitly mentioned in the model syntax.
```

## Modification indices
```{r}
#TBC...
```

## Extracting information from a fitted model
```{r}
#TBC...
```



